-- upgrade --
CREATE TABLE IF NOT EXISTS "category" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL UNIQUE,
    "path" VARCHAR(150) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "career" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL UNIQUE,
    "path" VARCHAR(150) NOT NULL UNIQUE,
    "category_id" INT NOT NULL REFERENCES "category" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "course" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL UNIQUE,
    "path" VARCHAR(150) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "user_profile" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "username" VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS "review" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "comment" TEXT NOT NULL,
    "stars" DECIMAL(2,1) NOT NULL,
    "course_id" INT NOT NULL REFERENCES "course" ("id") ON DELETE CASCADE,
    "user_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(20) NOT NULL,
    "content" JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS "course_career" (
    "course_id" INT NOT NULL REFERENCES "course" ("id") ON DELETE CASCADE,
    "career_id" INT NOT NULL REFERENCES "career" ("id") ON DELETE CASCADE
);
