#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
python << END
import sys
import asyncpg
import asyncio
import socket

async def try_connect():
    try:
        conn = await asyncpg.connect("${DATABASE_URL}")
    except:
        sys.exit(-1)
    await conn.close()
    sys.exit(0)

asyncio.get_event_loop().run_until_complete(try_connect())
END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
