entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    swarmMode: true
    exposedbydefault: false

certificatesResolvers:
  resolverhttps:
    acme:
      email: jmillan@vidaplatform.com
      storage: /ssl.json
      tlschallenge: true
      httpChallenge:
        entryPoint: web
